### PR TITLE
upgrade to holochain 0.2.6

### PR DESCRIPTION
**Pull request by nphias**
- npm updates to match 0.2x
- cargo and flake file updates
- sweettest works

### CODE REVIEW

**Comment by nphias** [comment]
remember to do:
`nix flake update`
the first time you run the upgrade otherwise nix wont use the holochain version specified in the flake file

**Comment by evomimic** [comment]
Thanks for the tip on `nix flake update`.

After `nix flake update`, I tried building this branch and got the following error:
"error: package `clap v4.5.4` cannot be built because it requires rustc 1.74 or newer, while the currently active rustc version is 1.72.1"

After updating rustc to 1.77.1, I get the following error:
"error: failed to run custom build command for `tx5-go-pion-sys v0.0.6-alpha`"

According to crates.io, `tx5-go-pion-sys` is a holochain crate that provides "Low level rust bindings to the go pion webrtc". library

**Comment by evomimic** [comment]
After upgrading my rust version from 1.72.1 to 1.77.1 and running `nix flake update` I was able to successfully build and test everything from the command line.  But when trying to build our happ in my IDE, I began seeing the following error: 

**error: failed to run custom build command for tx5-go-pion-sys v0.0.6-alpha**

Since CLI  runs fine, I figured the problem is due to some issue with my IDE config. But my IDE builds other branches in our repo just fine... it is just this branch with holochain upgrade that is having the problem. And I am encountering this error from BOTH IntelliJ IDEA 2023.3.2 (Community Edition) and RustRover 2023.3 EAP.  I tried clearing all caches and re-importing the project into my IDE as well as cleaning up my environment (by running `npx rimraf target && npx rimraf .cargo && npx rimraf Cargo.lock && npx rimraf flake.lock`) and re-building everything. CLI still worked fine. IDE's didn't.

Further investigation showed that tx5 error may be the result of a go version mismatch:
 ```
thread 'main' panicked at /Users/stevemelville/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tx5-go-pion-sys-0.0.6-alpha/build.rs:112:9:
  go executable version must be >= 1.20, got: 1.1
```

I downloaded and installed the latest go version and now I'm able to build from both IDE and CLI.

**Comment by evomimic** [comment]
Although sweetest now runs fine... my Rust Analyzer is still highlighting 2 problems in the holon_node.rs file:

Trait `From<LinkTypes>` is not implemented for `ScopedLinkType` [E0277]
Trait `From<LinkTypes>` is not implemented for `ScopedLinkType` [E0277]

Are you seeing this @nphias ?

**Pull request merged**
