### PR TITLE
145 extend implementation of smartlinks to support external references

### LINKED ISSUE #145: Extend implementation of SmartLinks to support External References
This enhancement adds encode/decode support for the `proxy_id` part of External HolonIds, so that SmartLinks fully support references to holon's in external HolonSpaces.

## Dependencies

- [x] Issue #142 

## Current State

Issue #142 generalized the definition of HolonId to cover both Local and External References. The latter includes a `proxy_id` that is not currently being encoded in the SmartLink's LinkTagObject.

The  `get_smartlink_from_link` function in smartlink.rs always returns a Local variant of HolonId for the to_address.

The `encode_link_tag` and `decode_link_tag` functions lack support for External HolonIds.

## Proposal

Add encode/decode support for the proxy_id part of External HolonId's so that SmartLinks fully support references to holon's in external HolonSpaces.

### In the smartlink.rs file

- [x] Extend the definition of LinkTagObject to (optionally) include a proxy_id.
     ```
     pub struct LinkTagObject {
          pub relationship_name: String,
          pub proxy_id: Option<HolonSpaceId>,
          pub smart_property_values: Option<PropertyMap>,
     }
     ```

- [x] Enhance the encode/decode functions to support encoding of proxy_id in the LinkTag per the [SmartLink encoding rules](https://github.com/evomimic/map-holons/wiki/SmartLink-Manager).

- [x] Enhance the `save_smartlink` function so that if the SmartLink's to_address is an External variant of HolonId, then encode its `proxy_id`  in the LinkTag.

- [x] Enhance the `get_smartlink_from_link` function to check if the LinkTag includes a `proxy_id` and, if so, to create a HolonId from the `local_target` plus the `proxy_id`.

## Testing

Integration test of this enhancement will have to wait until the ability to create and populate HolonSpaces has been added and the ability to add external references to relationships is supported. These tests will be included in a later issue when these dependencies have been satisfied.

- [ ] Enhance UnitTests to exercise the functional of creating and decoding SmartLinks with External HolonIds.

## Definition of Done

- [ ] Unit tests pass

### PR DESCRIPTION
**Pull request by dauphin3**
closes #145

### CODE REVIEW

**Comment by dauphin3** [comment]
@evomimic can you see if this compiles and passes... I'm getting a weird error about unable to compile holochain sqlite v0.3.2

**Comment by evomimic** [comment]
I noticed the last line in the above said: "-- `FIX_SQL_FMT=1 cargo build` to fix --",
so I tried the following `FIX_SQL_FMT=1  npm run sweetest` and everything compiled, the sweetests passed, but the unit test for encode_and_decode_link_tag failed:

running 1 test
test smartlink::tests::test_encode_and_decode_link_tag ... FAILED

failures:

---- smartlink::tests::test_encode_and_decode_link_tag stdout ----
thread 'smartlink::tests::test_encode_and_decode_link_tag' panicked at /Users/stevemelville/dev/map-proto/map-dev/map-holons/.cargo/registry/src/index.crates.io-6f17d22bba15001f/holo_hash-0.3.2/src/hash.rs:120:9:
assertion `left == right` failed: invalid byte count for HoloHash [117, 104, 67, 107, 107, 82, 67, 114, 87, 81, 81, 74, 57, 53, 100, 118, 119, 78, 68, 103, 71, 101, 82, 72, 119, 74, 81, 86, 106, 99, 114, 118, 75, 114, 109, 117, 68, 102, 54, 84, 48, 105, 121, 108, 105, 122, 69, 50, 103, 87, 121, 72, 67]
  left: 53
 right: 39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    smartlink::tests::test_encode_and_decode_link_tag

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

**Comment by evomimic** [comment]
## Why did FIX_SQL_STMT=1 correct the compile issue?

According to ChatGPT:
The error you’re encountering relates to an assertion in the lair_keystore build script (build.rs) that checks for consistency in the SQL schema formatting. Specifically, there is a mismatch between the expected format of the SQL statements and what is actually present in the code. The build script uses a formatting check for SQL files to ensure they match certain criteria, and in this case, the assertion is failing because the formatting of the SQL does not meet the expected format.

### Explanation of FIX_SQL_FMT=1

The environment variable FIX_SQL_FMT=1 allows the build process to automatically fix the SQL formatting issues. This build flag essentially tells the build script to rewrite the SQL files with the correct format rather than simply checking and throwing an error when it detects formatting differences.

The command: `FIX_SQL_FMT=1 cargo build` does two things.

1.	**Detects any SQL formatting issues**: It checks the SQL files referenced in the build script (like schema.sql, insert.sql, etc.) for specific formatting standards that the project enforces.
	2.	**Auto-corrects the SQL formatting:** When FIX_SQL_FMT=1 is set, it allows the build script to automatically modify these files to bring them in line with the expected format, thereby fixing the differences that caused the assertion failure.

### Why This Solved the Problem

In your case, the build script was expecting SQL statements to have a specific structure, likely related to indentation, whitespace, or some other minor formatting details. Without the FIX_SQL_FMT=1 flag, the script simply checks for these differences and panics if they don’t match. When you ran the build with this flag, the script fixed these formatting discrepancies, allowing the build to succeed.

### Takeaway

The root cause of the error was a formatting issue in one or more SQL files that the lair_keystore crate checks during the build process. By setting FIX_SQL_FMT=1, you allowed the build script to automatically reformat those files, ensuring they match the expected style and avoiding the assertion failure.

If you’d like to prevent this from happening again, you can check your SQL files manually for consistency with the formatting guidelines in the project. Alternatively, running the build with FIX_SQL_FMT=1 will continue to auto-correct these issues as they arise.

**Comment by dauphin3** [comment]
documenting our discussion here... 

a LocalId cannot be retrieved from a LinkTag, it is found in the to_address of the Link itself, therefore LinkTagObject returns a field of proxy_id: Option<HolonSpaceId> representing Some for an External reference_type and None for Local

**Comment by dauphin3** [comment]
@evomimic upon reflection, I remember my logic for using the default constructor for a mut LinkTagObject.. because of the if lets, the variables to populate the field are out of scope to create the object at the end of the function.

**Comment by evomimic** [comment]
> documenting our discussion here...
> 
> a LocalId cannot be retrieved from a LinkTag, it is found in the to_address of the Link itself, therefore LinkTagObject returns a field of proxy_id: Option representing Some for an External reference_type and None for Local

OK... we can leave things the way they are for now. 

I'm seeing LinkTagObject as just kind of an convenience data structure. We're not using it for encode and we could eliminate it on the decode side and just have pull the decode_link_tag logic  up into get_smartlink_from_link. But that would make get_smartlink_from_link longer, so I'm fine leaving it in place.

However, I did commit a few more changes to make the LinkTagObject and the helper functions private. This makes it clearer exactly which functions are intended for use by clients of smartlink.rs.




> @evomimic upon reflection, I remember my logic for using the default constructor for a mut LinkTagObject.. because of the if lets, the variables to populate the field are out of scope to create the object at the end of the function.

Ok... I have mild reservations about the structure of this code, but they are not serious enough to hold up this PR any further.

**Pull request merged**
